// Package config parses, validates, and serializes North configuration files.
package config

const (
	APIVersionV1Alpha1 = "north/v1alpha1"
	KindNorthConfig    = "NorthConfig"

	DefaultMaxParallel = 4
	MaxMaxParallel     = 64
)

type Config struct {
	APIVersion      string          `json:"apiVersion" yaml:"apiVersion"`
	Kind            string          `json:"kind" yaml:"kind"`
	Installation    Installation    `json:"installation" yaml:"installation"`
	Parallelization Parallelization `json:"parallelization" yaml:"parallelization"`
	Knowledge       Knowledge       `json:"knowledge" yaml:"knowledge"`
	Plugins         Plugins         `json:"plugins" yaml:"plugins"`
}

type Installation struct {
	Scope string `json:"scope" yaml:"scope"`
}

type Parallelization struct {
	Enabled             bool   `json:"enabled" yaml:"enabled"`
	Runtime             string `json:"runtime" yaml:"runtime"`
	Isolation           string `json:"isolation" yaml:"isolation"`
	Integration         string `json:"integration" yaml:"integration"`
	MaxParallel         int    `json:"maxParallel" yaml:"maxParallel"`
	FailFast            bool   `json:"failFast" yaml:"failFast"`
	AutoIntegrateTarget bool   `json:"autoIntegrateTarget" yaml:"autoIntegrateTarget"`
}

type Knowledge struct {
	Provider string `json:"provider" yaml:"provider"`
}

type Plugins struct {
	OpenCodeCodexMeter Plugin `json:"opencode-codex-meter" yaml:"opencode-codex-meter"`
	OpenLoop           Plugin `json:"@sbakolis/open-loop" yaml:"@sbakolis/open-loop"`
}

type Plugin struct {
	Enabled bool `json:"enabled" yaml:"enabled"`
}

// Default returns the normalized v1alpha1 configuration generated by North.
func Default() Config {
	return Config{
		APIVersion:   APIVersionV1Alpha1,
		Kind:         KindNorthConfig,
		Installation: Installation{Scope: "global"},
		Parallelization: Parallelization{
			Enabled: true, Runtime: "opencode-cli", Isolation: "git-worktree",
			Integration: "progressive", MaxParallel: DefaultMaxParallel,
		},
		Knowledge: Knowledge{Provider: "none"},
	}
}

// Options controls alpha parsing behavior.
type Options struct {
	Strict bool
}

type ParseOptions = Options

type Warning struct {
	Code    string `json:"code" yaml:"code"`
	Path    string `json:"path" yaml:"path"`
	Message string `json:"message" yaml:"message"`
}
